### ISSUE TITLE
Regression Testing for Shift Plot v2.0.0

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-shift-plot#21]
Confirm basic functionality and new features are working as expected in examples shown below:

Examples using v.2.0.0 Release Candidate
[default](http://bl.ocks.org/samussiah/raw/692aef6f9336258e529098b2e80f2d12/)
[customized](http://bl.ocks.org/samussiah/raw/ec77bf64b68cb6f9030a5749213de94e/)

**Basic Functionality (Tested every release)**
- [x] Check all spelling and grammar on the page
- [x] Confirm that measure filter is working as expected: plot points in the table and sites specified for collection both change
- [x] Confirm that visit filters are working as expected: plot points in the table and number of observations in the table header both change
- [x] Confirm that detailed record can be viewed by clicking and dragging the mouse across a section of values

**New Functionality (Tested in V.2.0.0 only)**
- [x] (#1) Confirm that x and y axes are equal
- [x] (#2) Confirm that when moused-over, the axis labels display tooltips containing visit information
- [x] (#8) Confirm that the # of enrolled/randomized participants is visible at the top of the page
- [x] (#9) Confirm that when selecting multiple filters, the axis ranges stay constant
- [x] (#10) Confirm that you can filter on the status of a participant (active, discontinued)

**Comment by samussiah** [comment]
[default](http://bl.ocks.org/samussiah/raw/692aef6f9336258e529098b2e80f2d12/)
[customized](http://bl.ocks.org/samussiah/raw/ec77bf64b68cb6f9030a5749213de94e/)

**Comment by brittsikora** [comment]
passed testing - closing
